### ISSUE TITLE
Frontend: show category page layout

### ISSUE THREAD

**Issue by alenavershinina** [Webmasters-Europe/codemeetup-forum#118]
Now at small screen column texts overlap:
![Снимок экрана от 2021-03-13 13-09-09](https://user-images.githubusercontent.com/74716234/111029558-9124ba80-83fd-11eb-8f1e-74ccd83db39d.png)

**Comment by RheaMars** [comment]
Fixed by https://github.com/Webmasters-Europe/codemeetup-forum/pull/242
