### ISSUE TITLE
Admin Area: Add some statistic data to the dashboard

### ISSUE THREAD

**Issue by RheaMars** [Webmasters-Europe/codemeetup-forum#155]
How many users joined the forum the last x days?
How many posts were created?
...

**Comment by RheaMars** [comment]
Maybe we wanna use https://github.com/asantibanez/livewire-charts for that?

**Comment by milack68** [comment]
- [ ] How many Users joined the forum the last x-days
- [ ] How many posts were created
- [ ] How many Categories were created
- [ ] How many Post-Replies were created

**Comment by milack68** [comment]
**Balkendiagramm(e)**

- [ ] Gesamtanzahl registrierte User
- [ ] Gesamtanzahl Moderatoren
- [ ] Gesamtanzahl Kategorien
- [ ] Gesamtanzahl Posts
- [ ] Gesamtanzahl PostReplies

**Liniendiagramm(e)**
6 Monate zurückblickend auf Monate aufgeteilt (die letzten 6 Monate sollen sich bei Monatswechsel immer anpassen)

- [ ] wie viele User haben sich registriert
- [ ] wie viele Posts wurden geschrieben
- [ ] wie viele Replies wurden geschrieben#

**Liste der Top 5 (Pie-Charts)**

- [ ] User mit den meisten Posts
- [ ] User mit den meisten Replies
