### ISSUE TITLE
login auch mit username

### ISSUE THREAD

**Issue by milack68** [Webmasters-Europe/codemeetup-forum#22]
Ein Benutzer kann sich in der Laravel Standard Authentifizierung nur mit E-Mail-Adresse und Passwort einloggen. 

Benutzer sollten die Möglichkeit haben, sich alternativ mit Username oder E-Mail-Adresse und jeweils mit Passwort einzuloggen.

Dazu ist einerseits die Änderung der Registrierung (Feld "username") als auch des Logins notwendig.

**Comment by milack68** [comment]
@Cosnavel : Ich würde gerne diese Aufgabe übernehmen. Wenn du es aber für besser hältst bis Samstag zu warten um gemeinsam zu beginnen, auch kein Problem.

**Comment by Cosnavel** [comment]
Nope go for it ✌🏻🚀

Leg bitte ne Feature Branch an.

**Comment by Cosnavel** [comment]
Ref #27
