### ISSUE TITLE
Admin Area not available on https://codemeetup-forum.webmasters-akademie.dev/

### ISSUE THREAD

**Issue by milack68** [Webmasters-Europe/codemeetup-forum#234]
Error 500

**Comment by Cosnavel** [comment]
Todo @Cosnavel 

- [ ] refactor every raw query
- [ ] refactor to collection to reduce query size

**Comment by milack68** [comment]
The entire website returns an error 500.

**Comment by RheaMars** [comment]
Fixed by https://github.com/Webmasters-Europe/codemeetup-forum/pull/243 and https://github.com/Webmasters-Europe/codemeetup-forum/pull/237. I'll create a new ticket for the current 500 error.
