### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by Cosnavel** [Webmasters-Europe/codemeetup-forum#26]
- [x] Add Code Quality Pipeline
- [x] Add php-cs-fixer
- [x] Add Prettier
- [x] Add CI
- [x] Add Deployment Pipeline

**Comment by milack68** [comment]
@Cosnavel Diesen issue könnten wir schließen, da er von dir bereits umgesetzt und auch gemergt wurde, oder?

**Comment by Cosnavel** [comment]
@milack68 Nein habe noch keine Deployment Pipeline eingebaut
