### ISSUE TITLE
Frontend (Startseite) mobile Ansicht aufbauen

### ISSUE THREAD

**Issue by thelf** [Webmasters-Europe/codemeetup-forum#30]
Für die mobile Darstellung des Frontend-Layouts sollten die cols untereinander stehen.

Image
Titel des Threads
Anzahl der Beiträge
Letzte Nachrichten

Als Beispiel:

```
<div class="row">
  <div class="col-12">Image</div>
  <div class="col-12">Titel des Threads</div>
  <div class="col-12">Anzahl der Beiträge</div>
  <div class="col-12">Letzte Nachrichten</div>
</div>
```
Jetzt würde jede col 100% Breite des Viewports verwenden und alle cols untereinander stehen.

Durch die Verwendung von Klassen als Breakpoints kann jetzt gesteuert werden wie sich die cols anordnen.

Beispiel mit der Klasse .sm:

```
<div class="row">
  <div class="col-12  col-sm-6">Image</div>
  <div class="col-12  col-sm-6">Titel des Threads</div>
  <div class="col-12  col-sm-6">Anzahl der Beiträge</div>
  <div class="col-12  col-sm-6">Letzte Nachrichten</div>
</div>
```

Ab dem Breakpoint > 576px würden jetzt 2 cols nebeneinander stehen.

Images                          |  Titel des Threads
Anzahle der Beiträge    |  Letzte Nachrichten

Es gibt folgende Standard Klassen von Bootstrap:
xs >    0px
sm >  576px
md > 768px
lg >    992px
xl  >   1200px

Quelle: https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works

**Comment by alenavershinina** [comment]
Hi, Thomas, meine Idee sieht so aus:
```
<div class="row">
  <div class="col-3  col-lg-2">Image</div>
  <div class="col-6  col-lg-4">Titel des Threads</div>
  <div class="col-3  col-lg-2">Anzahl der Beiträge</div>
  <div class="col-12  col-lg-4">Letzte Nachrichten</div>
</div>
```
Wir muessen noch Schriftgroesse einstellen, aber etwas wie hier:
![Снимок экрана от 2021-02-15 21-24-56](https://user-images.githubusercontent.com/74716234/107990266-56815b00-6fd4-11eb-9b36-6595f6f462f8.png)
![Снимок экрана от 2021-02-15 21-24-27](https://user-images.githubusercontent.com/74716234/107990269-57b28800-6fd4-11eb-8f22-826295739a49.png)

**Comment by Cosnavel** [comment]
Wonach soll die Suchfunktion alles Suchen? Haben wir dazu schon eine Discussion oder ein Issue?

**Comment by alenavershinina** [comment]
> Wonach soll die Suchfunktion alles Suchen? Haben wir dazu schon eine Discussion oder ein Issue?

Nein, wir haben ueber Suchfunktion nicht diskutiert.

**Comment by thelf** [comment]
> Hi, Thomas, meine Idee sieht so aus:
> 
> ```
> <div class="row">
>   <div class="col-3  col-lg-2">Image</div>
>   <div class="col-6  col-lg-4">Titel des Threads</div>
>   <div class="col-3  col-lg-2">Anzahl der Beiträge</div>
>   <div class="col-12  col-lg-4">Letzte Nachrichten</div>
> </div>
> ```
> 
> Wir muessen noch Schriftgroesse einstellen, aber etwas wie hier:
> ![Снимок экрана от 2021-02-15 21-24-56](https://user-images.githubusercontent.com/74716234/107990266-56815b00-6fd4-11eb-9b36-6595f6f462f8.png)
> ![Снимок экрана от 2021-02-15 21-24-27](https://user-images.githubusercontent.com/74716234/107990269-57b28800-6fd4-11eb-8f22-826295739a49.png)

Hallo Alena,

das gefällt mir sehr gut!
