### ISSUE TITLE
Frontend (Startseite) Layout für Desktop Ansicht aufbauen

### ISSUE THREAD

**Issue by thelf** [Webmasters-Europe/codemeetup-forum#36]
Anordnung des Content Bereichs links und rechts daneben die Sidebar für die Desktop Ansicht.

**Comment by Cosnavel** [comment]
@thelf kannst du dafür ggf ein Mockup oder eine Skizze bauen?

**Comment by thelf** [comment]
@Cosnavel, @alenavershinina hat das schon als Scribble aufgebaut in Issue #14 im ersten Screen.

**Comment by thelf** [comment]
Ich würde das umsetzen.

**Comment by alenavershinina** [comment]
@thelf Habe ich richtig verstanden, dass du jetzt dieses Mittelelement(wo Login feld liegt) responsive machen willst? so, dass es auf large Bildschirm nach recht geht?

**Comment by thelf** [comment]
@alenavershinina 
Ja genau, die Seite würde dann für Desktop so aussehen wie in deinem Scribble. Ich bin noch nicht ganz fertig, aber im Moment sieht es so aus:

![layout](https://user-images.githubusercontent.com/29478738/108063752-fb934680-705b-11eb-9cc3-9f819aada4be.JPG)

**Comment by thelf** [comment]
und mobile wie bisher:

![mobile](https://user-images.githubusercontent.com/29478738/108063884-2d0c1200-705c-11eb-8704-73265366efb4.JPG)
