### ISSUE TITLE
Add last entries in sidebar

### ISSUE THREAD

**Issue by thelf** [Webmasters-Europe/codemeetup-forum#61]
Details in Frontend scribble #14

**Comment by milack68** [comment]
@thelf Thomas, willst du diesen Issue gleich übernehmen? Dann würde ich ihn dir zuweisen. Somit haben wir dann immer einen Überblick, wer an welchem Issue arbeitet.

**Comment by thelf** [comment]
Das können wir gerne machen Michael @milack68 .
