### ISSUE TITLE
Improve Styling Searchbar

### ISSUE THREAD

**Issue by Cosnavel** [Webmasters-Europe/codemeetup-forum#96]
Current Style with and without search results
<img width="422" alt="CleanShot 2021-03-06 at 10 26 54@2x" src="https://user-images.githubusercontent.com/42392570/110221193-1292bf00-7ecb-11eb-9706-df23393fba3e.png">
<img width="229" alt="CleanShot 2021-03-06 at 10 27 07@2x" src="https://user-images.githubusercontent.com/42392570/110221196-19b9cd00-7ecb-11eb-8dfa-46aa0113a1b7.png">

I think we should improve the styling here @alenavershinina @thelf

**Comment by thelf** [comment]
Yes you are right, i can do that.
